web:
  image: nginx
  ports:
   - "8080:80"
  environment:
   - NGINX_HOST=www.server.com
   - NGINX_PORT=80
   - APP_PORT=50021
  command: /bin/bash -c "source /etc/profile && npm run deploy-prod && envsubst < /etc/nginx/conf.d/server.conf.template  > /etc/nginx/conf.d/server.conf && nginx -g 'daemon off;'"